name: ci

on: [push, pull_request]

env:
  MONGODB_VERSION: 5.0.6
  MONGODB_DB_NAME: ns-${{ github.sha }}-${{ github.run_id }}
  MONGODB_REPLICA_SET: newshades-gh-replica
  REDIS_VERSION: 6.2.6
  PYTHON_VERSION: 3.9.12

jobs:
  build:
    name: ci
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install poetry
      run: curl -sL https://install.python-poetry.org | python -

    - name: Update PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Configure poetry
      run: poetry config virtualenvs.in-project true

    - name: Set up cache
      uses: actions/cache@v2
      id: cache
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Ensure cache is healthy
      if: steps.cache.outputs.cache-hit == 'true'
      run: timeout 10s poetry run pip --version || rm -rf .venv

    - name: Install dependencies
      run: poetry install

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ env.MONGODB_VERSION }}
        mongodb-replica-set: ${{ env.MONGODB_REPLICA_SET }}

    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: ${{ env.REDIS_VERSION }}

    - name: Run tests >> pytest
      env:
        PUSHER_APP_ID: ${{ secrets.PUSHER_APP_ID }}
        PUSHER_KEY: ${{ secrets.PUSHER_KEY }}
        PUSHER_SECRET: ${{ secrets.PUSHER_SECRET }}
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        MONGODB_TEST_DB: ${{ env.MONGODB_DB_NAME }}
        ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
        WEB3_PROVIDER_URL_WS: ${{ secrets.WEB3_PROVIDER_URL_WS }}
      run: poetry run python -m pytest -rf --cov=./ --cov-report=xml

    - name: Upload coverage
      uses: codecov/codecov-action@v3.1.0
